export const actions = {
    click: "click",
    load: "navigate",
    keypress: "fill_field",
    CREATE_ANNOTATION: 'apply_annotation',
    ELEMENT_SCREENSHOT: 'element_screenshot',
    FULL_SCREEN_SCREENSHOT: "full_screen_screenshot",
    BADGE: 'badge',
    OUTLINE: 'outline',
    BADGE_OUTLINE: 'badge_outline',
    BLUR: 'blur',
    BADGE_BLUR: 'badge_blur',

    TEST_SELECTOR: 'TEST_SELECTOR',
    ITEM_SELECTED: 'ITEM_SELECTED',
    GET_AUTH: 'getAuth',
    SAVE_STEP: "save_step",
    GET_CLICKED_ELEMENT: "get_clicked_element",
    START_RUNNING: "START_RUNNING",
    STOP_RUNNING: "STOP_RUNNING",
    HIGHLIGHT_ELEMENT: "HIGHLIGHT_ELEMENT",
    UNHIGHLIGHT_ELEMENT: "UNHIGHLIGHT_ELEMENT",
    APPLY_ANNOTATION: "APPLY_ANNOTATION",
    REMOVE_ANNOTATION: "REMOVE_ANNOTATION",
    START: 'START',
    STOP: 'STOP'
  }